import "./globals.css";
import type { Metadata } from "next";
import { yekan } from "@/utils/fonts";
import Layout from "@/layout//Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="box-border max-w-screen-xl mx-auto " lang="fa" dir="rtl">
      <body className={yekan.className}>
        <Layout >{children}</Layout>
      </body>
    </html>
  );
}
